//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Categoria
{
    public int id_categoria { get; set; }
    public string nombre { get; set; }
}

public partial class Cliente
{
    public int id_cliente { get; set; }
    public string nombre { get; set; }
    public string direccion { get; set; }
    public Nullable<long> numero_telefono { get; set; }
    public string correo { get; set; }
    public Nullable<int> id_equipo { get; set; }
}

public partial class Comision
{
    public int id_comision { get; set; }
    public string nombre { get; set; }
    public Nullable<double> porcentaje { get; set; }
}

public partial class Equipo
{
    public int id_equipo { get; set; }
    public string nombre { get; set; }
    public Nullable<int> cant_jugadores { get; set; }
}

public partial class Queja
{
    public int id_queja { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string detalle { get; set; }
    public Nullable<int> id_vendedor { get; set; }
    public Nullable<int> id_cliente { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tblArticulo
{
    public int id_articulo { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public string color { get; set; }
    public string tamano { get; set; }
    public Nullable<int> precio { get; set; }
    public Nullable<int> coste_u_mayorista { get; set; }
    public Nullable<int> unidades { get; set; }
    public Nullable<int> id_categoria { get; set; }
    public Nullable<bool> eliminado { get; set; }
}

public partial class tblPedido
{
    public int id_pedido { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<int> total { get; set; }
    public Nullable<int> id_vendedor { get; set; }
    public int id_cliente { get; set; }
    public Nullable<byte> existencia { get; set; }
}

public partial class tblPedido_Articulos
{
    public long id_pedido_articulos { get; set; }
    public Nullable<int> id_pedido { get; set; }
    public Nullable<int> id_articulo { get; set; }
    public string tamano_articulo { get; set; }
    public string color_articulo { get; set; }
    public Nullable<int> unidades_articulo { get; set; }
    public Nullable<int> precio_u_articulo { get; set; }
    public Nullable<bool> estado { get; set; }
}

public partial class Vendedor
{
    public int id_vendedor { get; set; }
    public string nombre { get; set; }
    public string direccion { get; set; }
    public Nullable<long> numero_telefono { get; set; }
    public string correo { get; set; }
    public Nullable<int> id_comision { get; set; }
}
