//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class DB_PAAC4G4ArriagadaSepulvedaVidalEntities : DbContext
{
    public DB_PAAC4G4ArriagadaSepulvedaVidalEntities()
        : base("name=DB_PAAC4G4ArriagadaSepulvedaVidalEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Categoria> Categoria { get; set; }
    public virtual DbSet<Cliente> Cliente { get; set; }
    public virtual DbSet<Comision> Comision { get; set; }
    public virtual DbSet<Equipo> Equipo { get; set; }
    public virtual DbSet<Queja> Queja { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<tblPedido_Articulos> tblPedido_Articulos { get; set; }
    public virtual DbSet<Vendedor> Vendedor { get; set; }
    public virtual DbSet<tblArticulo> tblArticulo { get; set; }
    public virtual DbSet<tblPedido> tblPedido { get; set; }

    public virtual int pa_listarPedidoArticulosPorPedido(Nullable<int> id_pedido)
    {
        var id_pedidoParameter = id_pedido.HasValue ?
            new ObjectParameter("id_pedido", id_pedido) :
            new ObjectParameter("id_pedido", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_listarPedidoArticulosPorPedido", id_pedidoParameter);
    }
}
